// *********************************************************************************************
//                 WARNING: AUTO-GENERATED FILE, DO NOT MODIFY IT.
//
// This file has been generated by fortran_to_c_headers version 0.1
// For more information visit https://github.com/sharifmarat/fortran_to_c_headers
// *********************************************************************************************
#ifndef RESULT_H
#define RESULT_H

#ifdef __cplusplus
extern "C"
{
#endif

#ifdef __cplusplus
}
#endif

#endif //RESULT_H
